class AppStrings {
  AppStrings._();

  static bool isGujarati = true;

  static String get(String key) {
    return isGujarati ? _gu[key] ?? _en[key] ?? key : _en[key] ?? key;
  }

  static const Map<String, String> _gu = {
    // App
    'app_name': 'હિસાબ કિતાબ',
    'tagline': 'દર પૈસાનો હિસાબ',

    // Navigation
    'home': 'હોમ',
    'transactions': 'વ્યવહારો',
    'ledger': 'ઉધાર-ઉઘરાણી',
    'reports': 'રિપોર્ટ',
    'settings': 'સેટિંગ',

    // Dashboard
    'total_balance': 'કુલ બાકી',
    'this_month': 'આ મહિનો',
    'total_income': 'કુલ આવક',
    'total_expense': 'કુલ ખર્ચ',
    'recent_txns': 'તાજેતરના વ્યવહારો',

    // Transaction
    'income': 'આવક',
    'expense': 'ખર્ચ',
    'amount': 'રકમ',
    'category': 'વર્ગ',
    'account': 'ખાતું',
    'date': 'તારીખ',
    'note': 'નોંધ',
    'add_income': 'આવક ઉમેરો',
    'add_expense': 'ખર્ચ ઉમેરો',
    'edit_transaction': 'વ્યવહાર સુધારો',
    'delete_transaction': 'ડિલીટ કરો',
    'save': 'સાચવો',
    'cancel': 'રદ',
    'update': 'સુધારો',

    // Categories — Income
    'cat_salary': 'પગાર',
    'cat_business': 'ધંધો',
    'cat_investment': 'રોકાણ',
    'cat_gift': 'ભેટ',
    'cat_other_income': 'અન્ય આવક',

    // Categories — Expense
    'cat_food': 'ખાણી-પીણી',
    'cat_transport': 'વાહન-વ્યવહાર',
    'cat_shopping': 'શોપિંગ',
    'cat_health': 'આરોગ્ય',
    'cat_education': 'શિક્ષણ',
    'cat_entertainment': 'મનોરંજન',
    'cat_rent': 'ભાડું',
    'cat_electricity': 'વીજળી/પાણી',
    'cat_mobile': 'મોબાઈલ/ઇન્ટરનેટ',
    'cat_grocery': 'કરિયાણા',
    'cat_other_expense': 'અન્ય ખર્ચ',

    // Accounts
    'cash': 'રોકડ',
    'bank': 'બેન્ક',
    'upi': 'UPI / વૉલેટ',
    'add_account': 'ખાતું ઉમેરો',

    // Ledger
    'ledger_title': 'ઉધાર-ઉઘરાણી',
    'gave_money': 'આપ્યા',
    'took_money': 'લીધા',
    'add_person': 'વ્યક્તિ ઉમેરો',
    'add_loan': 'ઉધાર ઉમેરો',
    'add_payment': 'હપ્તો નોંધો',
    'principal': 'મૂળ રકમ',
    'interest_rate': 'વ્યાજ દર (%)',
    'interest_type': 'વ્યાજ પ્રકાર',
    'simple_interest': 'સાદું વ્યાજ',
    'compound_interest': 'ચક્રવૃદ્ધિ વ્યાજ',
    'flat_rate': 'ફ્લૅટ રેટ (EMI)',
    'emi_amount': 'EMI રકમ',
    'total_months': 'કુલ મહિના',
    'fixed_emi': 'Fixed EMI',
    'flexible': 'ગમે ત્યારે',
    'outstanding': 'બાકી રકમ',
    'interest_accrued': 'ઉઘરાણું વ્યાજ',
    'paid_amount': 'ભરેલી રકમ',
    'loan_closed': 'ઉધાર બંધ',
    'loan_active': 'ઉધાર ચાલુ',

    // Reports
    'monthly_report': 'માસિક રિપોર્ટ',
    'category_report': 'વર્ગ-વાર ખર્ચ',
    'export_pdf': 'PDF Export',
    'export_excel': 'Excel Export',

    // Settings
    'language': 'ભાષા',
    'theme': 'થીમ',
    'light_theme': 'હળવી',
    'dark_theme': 'ઘેરી',
    'system_theme': 'ઓટો',
    'pin_lock': 'PIN Lock',
    'backup': 'બૅકઅપ',
    'restore': 'રીસ્ટૉર',
    'take_backup': 'બૅકઅપ લો',
    'restore_backup': 'બૅકઅપ રીસ્ટૉર',
    'backup_success': 'બૅકઅપ સફળ!',
    'restore_success': 'ડેટા રીસ્ટૉર થઈ ગયો!',

    // Errors / Validation
    'required_field': 'આ ખાનું ભરવું જરૂરી છે',
    'invalid_amount': 'સાચી રકમ લખો',
    'amount_zero': 'રકમ 0 થી વધુ હોવી જોઈએ',
    'delete_confirm': 'ડિલીટ કરવું છે?',
    'yes': 'હા',
    'no': 'ના',
    'no_data': 'કોઈ ડેટા નથી',
    'no_transactions': 'કોઈ વ્યવહાર નથી\n+ બટન દબાવી ઉમેરો',
  };

  static const Map<String, String> _en = {
    'app_name': 'Hisaab Kitaab',
    'tagline': 'Track Every Rupee',
    'home': 'Home',
    'transactions': 'Transactions',
    'ledger': 'Ledger',
    'reports': 'Reports',
    'settings': 'Settings',
    'total_balance': 'Total Balance',
    'this_month': 'This Month',
    'total_income': 'Total Income',
    'total_expense': 'Total Expense',
    'recent_txns': 'Recent Transactions',
    'income': 'Income',
    'expense': 'Expense',
    'amount': 'Amount',
    'category': 'Category',
    'account': 'Account',
    'date': 'Date',
    'note': 'Note',
    'add_income': 'Add Income',
    'add_expense': 'Add Expense',
    'edit_transaction': 'Edit Transaction',
    'delete_transaction': 'Delete',
    'save': 'Save',
    'cancel': 'Cancel',
    'update': 'Update',
    'cat_salary': 'Salary',
    'cat_business': 'Business',
    'cat_investment': 'Investment',
    'cat_gift': 'Gift',
    'cat_other_income': 'Other Income',
    'cat_food': 'Food & Drinks',
    'cat_transport': 'Transport',
    'cat_shopping': 'Shopping',
    'cat_health': 'Health',
    'cat_education': 'Education',
    'cat_entertainment': 'Entertainment',
    'cat_rent': 'Rent',
    'cat_electricity': 'Electricity/Water',
    'cat_mobile': 'Mobile/Internet',
    'cat_grocery': 'Grocery',
    'cat_other_expense': 'Other Expense',
    'cash': 'Cash',
    'bank': 'Bank',
    'upi': 'UPI / Wallet',
    'add_account': 'Add Account',
    'ledger_title': 'Ledger',
    'gave_money': 'Given',
    'took_money': 'Taken',
    'add_person': 'Add Person',
    'add_loan': 'Add Loan',
    'add_payment': 'Record Payment',
    'principal': 'Principal Amount',
    'interest_rate': 'Interest Rate (%)',
    'interest_type': 'Interest Type',
    'simple_interest': 'Simple Interest',
    'compound_interest': 'Compound Interest',
    'flat_rate': 'Flat Rate (EMI)',
    'emi_amount': 'EMI Amount',
    'total_months': 'Total Months',
    'fixed_emi': 'Fixed EMI',
    'flexible': 'Flexible',
    'outstanding': 'Outstanding',
    'interest_accrued': 'Interest Accrued',
    'paid_amount': 'Paid Amount',
    'loan_closed': 'Closed',
    'loan_active': 'Active',
    'monthly_report': 'Monthly Report',
    'category_report': 'Category Report',
    'export_pdf': 'Export PDF',
    'export_excel': 'Export Excel',
    'language': 'Language',
    'theme': 'Theme',
    'light_theme': 'Light',
    'dark_theme': 'Dark',
    'system_theme': 'System',
    'pin_lock': 'PIN Lock',
    'backup': 'Backup',
    'restore': 'Restore',
    'take_backup': 'Take Backup',
    'restore_backup': 'Restore Backup',
    'backup_success': 'Backup Successful!',
    'restore_success': 'Data Restored!',
    'required_field': 'This field is required',
    'invalid_amount': 'Enter valid amount',
    'amount_zero': 'Amount must be greater than 0',
    'delete_confirm': 'Delete this?',
    'yes': 'Yes',
    'no': 'No',
    'no_data': 'No data found',
    'no_transactions': 'No transactions\nTap + to add one',
  };
}
